openapi: 3.1.0
info:
  title: Gate.io Proxy API (Render)
  version: "1.0.0"
  description: |
    واجهة بروكسي للقراءة من Gate.io عبر خادم Render.
    جميع المسارات هنا **قراءة فقط** ولا تُحدث حساب المستخدم.
servers:
  - url: https://gateio-proxy-v2.onrender.com
    description: Render Production

paths:
  /proxy/health:
    get:
      summary: فحص صحة الخدمة
      operationId: getHealth
      responses:
        "200":
          description: معلومات بسيطة عن صحة الخدمة
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    description: هل الخدمة تعمل
                  service:
                    type: string
                    description: اسم الخدمة
                  time:
                    type: string
                    description: التوقيت الحالي على الخادم (ISO-8601)
                required: [ok, service, time]
              examples:
                default:
                  value: { ok: true, service: "gateio-proxy", time: "2025-08-16T12:34:56Z" }

  /proxy/balances:
    get:
      summary: الحصول على أرصدة المحفظة
      operationId: getBalances
      responses:
        "200":
          description: قائمة الأرصدة المتاحة
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Balance"
              examples:
                sample:
                  value:
                    - currency: "USDT"
                      available: "1234.56"
                      frozen: "0.00"
                      total: "1234.56"
                    - currency: "BTC"
                      available: "0.015"
                      frozen: "0.000"
                      total: "0.015"
        "502":
          $ref: "#/components/responses/UpstreamError"

  # (اختياري) فحص صحة السيرفر بدون بروكسي
  /healthz:
    get:
      summary: فحص صحة السيرفر (محلي)
      operationId: getHealthz
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  service: { type: string }
                  ts: { type: number }
                required: [ok, service]

  # (اختياري) فحص اتصال Gate.io عبر الوكيل بدون مفاتيح
  /proxy/healthz:
    get:
      summary: فحص الاتصال بـ Gate.io عبر الوكيل (بدون مفاتيح)
      operationId: getProxyHealthz
      responses:
        "200":
          description: Upstream status
          content:
            application/json:
              schema:
                type: object
                properties:
                  upstream: { type: boolean }
                  status: { type: integer, nullable: true }
                  error: { type: string, nullable: true }
                  checked_endpoint: { type: string }
                required: [upstream, checked_endpoint]
          # في حال أردت تعريف خطأ موحد أيضًا:
        "502":
          $ref: "#/components/responses/UpstreamError"

components:
  schemas:
    Balance:
      type: object
      description: رصيد عملة واحدة
      properties:
        currency:
          type: string
          description: رمز العملة (USDT, BTC, ...)
        available:
          type: string
          description: الرصيد المتاح
        frozen:
          type: string
          description: الرصيد المجمد/المحجوز
        total:
          type: string
          description: إجمالي الرصيد (available + frozen)
      required: [currency, available, frozen, total]

  responses:
    UpstreamError:
      description: فشل استدعاء الخدمة الخارجية (Gate.io)
      content:
        application/json:
          schema:
            type: object
            properties:
              upstream:
                type: boolean
                description: هل الاتصال بالمصدر الخارجي متاح
              status:
                type: integer
                nullable: true
                description: كود HTTP من المصدر الخارجي إن توفّر
              error:
                type: string
                nullable: true
                description: رسالة خطأ مختصرة
              checked_endpoint:
                type: string
                description: المسار الذي تم فحصه في المصدر الخارجي
            required: [upstream, checked_endpoint]
          examples:
            example502:
              value:
                upstream: false
                status: 502
                error: "Bad Gateway or timeout"
                checked_endpoint: "/api/v4/spot/currency_pairs"
