openapi: 3.1.0
info:
  title: Gate.io Proxy API
  description: واجهة بروكسي للاتصال بـ Gate.io عبر OpenAI GPT Actions
  version: 1.0.0
servers:
  - url: https://gateio-proxy-v2.onrender.com
paths:
  /proxy/balances:
    get:
      summary: عرض الأرصدة
      operationId: getBalances
      responses:
        '200':
          description: قائمة الأرصدة
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    currency:
                      type: string
                    available:
                      type: string
                    locked:
                      type: string

  /proxy/orders:
    post:
      summary: إنشاء أمر جديد (شراء/بيع)
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currency_pair:
                  type: string
                  example: BTC_USDT
                type:
                  type: string
                  example: market
                side:
                  type: string
                  example: buy
                amount:
                  type: string
                  example: "0.001"
                price:
                  type: string
                  example: "30000"
      responses:
        '200':
          description: تفاصيل الأمر
          content:
            application/json:
              schema:
                type: object

  /proxy/orders/history:
    get:
      summary: عرض سجل الأوامر
      operationId: getOrdersHistory
      responses:
        '200':
          description: أوامر سابقة
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
