  /proxy/orders:
    post:
      summary: إنشاء أمر جديد (شراء/بيع)
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currency_pair:
                  type: string
                  example: BTC_USDT
                type:
                  type: string
                  example: market
                side:
                  type: string
                  example: buy
                amount:
                  type: string
                  example: "0.001"
                price:
                  type: string
                  example: "30000"
      responses:
        '200':
          description: تفاصيل الأمر
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: معرف الأمر
                  status:
                    type: string
                    description: حالة الأمر (مثال: open, closed, finished)
                  currency_pair:
                    type: string
                  type:
                    type: string
                  side:
                    type: string
                  amount:
                    type: string
                  price:
                    type: string
