openapi: 3.1.0
info:
  title: Gate.io Proxy API
  description: واجهة بروكسي للاتصال بـ Gate.io عبر OpenAI GPT Actions
  version: 1.0.0

servers:
  - url: https://gateio-proxy.onrender.com

paths:
  /proxy/balances:
    get:
      summary: الحصول على أرصدة المحفظة
      operationId: getBalances
      responses:
        '200':
          description: قائمة الأرصدة
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    currency:
                      type: string
                    available:
                      type: string
                    locked:
                      type: string

  /proxy/orders:
    post:
      summary: إنشاء أمر شراء/بيع
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currency_pair:
                  type: string
                  example: BTC_USDT
                type:
                  type: string
                  example: market
                side:
                  type: string
                  example: buy
                amount:
                  type: string
                  example: "0.001"
                price:
                  type: string
                  example: "30000"
      responses:
        '200':
          description: تفاصيل الأمر
          content:
            application/json:
              schema:
                type: object

  /proxy/orders/open:
    get:
      summary: الأوامر المفتوحة
      operationId: listOpenOrders
      responses:
        '200':
          description: قائمة الأوامر المفتوحة
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /proxy/orders/history:
    get:
      summary: سجل الأوامر
      operationId: listOrderHistory
      responses:
        '200':
          description: قائمة الأوامر المنفذة
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /proxy/orders/{id}:
    delete:
      summary: إلغاء أمر
      operationId: cancelOrder
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: نتيجة الإلغاء
